apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tamagotchi-data
  labels:
    app: tamagotchi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 1Gi
