---
apiVersion: v1
kind: Namespace
metadata:
  name: romm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: romm
  namespace: romm
  labels:
    app: romm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romm
  template:
    metadata:
      labels:
        app: romm
    spec:
      containers:
      - name: romm
        image: rommapp/romm:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          value: "romm-db"
        - name: DB_NAME
          value: "romm"
        - name: DB_USER
          value: "romm-user"
        - name: DB_PASSWD
          value: "romm-password"
        - name: ROMM_AUTH_SECRET_KEY
          value: "your-secret-key-here"
        volumeMounts:
        - name: romm-library
          mountPath: /romm/library
        - name: romm-resources
          mountPath: /romm/resources
        - name: romm-config
          mountPath: /romm/config
      volumes:
      - name: romm-library
        emptyDir: {}
      - name: romm-resources
        emptyDir: {}
      - name: romm-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: romm
  namespace: romm
  labels:
    app: romm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: romm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: romm
  namespace: romm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
  - host: romm.192.168.0.77.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: romm
            port:
              number: 80
  tls:
  - hosts:
    - romm.192.168.0.77.sslip.io
    secretName: romm-tls

