apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masterclass-storage
  namespace: default
  labels:
    app: masterclass-downloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: proxmox-csi-moviedrive

