apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    chart: proxmox-csi-plugin
    targetRevision: 0.3.16         # pick a version that works, or use “latest” carefully
    helm:
      values: |
        # proxmox-csi.yaml
        config:
          clusters:
            - url: https://192.168.0.77:8006/api2/json
              insecure: true
              token_id: "kubernetes-csi@pve!csi" 
              token_secret: "67e608b1-8147-4fed-b873-35795240673d"
              region: Homelab
        storageClass:
          - name: proxmox-csi
            storage: local-lvm
            reclaimPolicy: Delete
            fstype: ext4
            # Define the storage class as default
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
        # Let it run on the control plane
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
          - key: node-role.kubernetes.io/master
            operator: Exists
        node:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-proxmox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 



