apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emulatorjs
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: emulatorjs
  source:
    chart: emulatorjs
    repoURL: oci://oci.trueforge.org/truecharts/emulatorjs
    targetRevision: 12.8.0       # ✅ Check TrueCharts for latest version
    helm:
      skipCrds: false
      skipDependencies: false    # ✅ Important
      values: |
        image:
          repository: ghcr.io/linuxserver/emulatorjs
          tag: latest
          pullPolicy: IfNotPresent

        persistence:
          enabled: true
          data:
            enabled: true
            size: 10Gi
            storageClass: "local-path"    # ✅ Works for Proxmox/k3s
            accessModes:
              - ReadWriteOnce

        service:
          type: ClusterIP
          port: 80

        ingress:
          enabled: true
          hosts:
            - host: emulator.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - emulator.example.com
              secretName: emulatorjs-tls
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: "50m"

        timezone: "Europe/Berlin"

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true