apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.2.3
    helm:
      values: |
        crds:
          install: false
        admissionController:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
        backgroundController:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
        cleanupController:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
        reportsController:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true


