apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.3         # pick a version that works, or use “latest” carefully
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
            loadBalancerIP: 192.168.0.241
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          admissionWebhooks:
            enabled: true
            certManager:
              enabled: false
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            patch:
                enabled: true
                tolerations:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
            - key: node-role.kubernetes.io/master
              operator: Exists
        defaultBackend:
          enabled: true
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
            - key: node-role.kubernetes.io/master
              operator: Exists
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "100m"
        controller:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 