apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.3         # pick a version that works, or use “latest” carefully
    helm:
      values: |
        controller:
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          admissionWebhooks:
            enabled: true
            certManager:
              enabled: false
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            patch:
                enabled: true
                tolerations:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists



          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
            - key: node-role.kubernetes.io/master
              operator: Exists
        defaultBackend:
          enabled: true
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
            - key: node-role.kubernetes.io/master
              operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 