apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.3         # pick a version that works, or use “latest” carefully
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
        defaultBackend:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 