apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: 1.1.3         # pick a version that works, or use “latest” carefully
    helm:
      values: |
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
          - key: node-role.kubernetes.io/master
            operator: Exists
        ingress:
          # -- Specify if an ingress resource for the pms server should be created or not
          enabled: true

          # -- The ingress class that should be used
          ingressClassName: "nginx"

          # -- The url to use for the ingress reverse proxy to point at this pms instance
          url: "plex.192.168.0.77.sslip.io"

          # -- Optional TLS configuration to provide valid https connections
          # using an existing SSL certificate
          tls: []
          #   - hosts:
          #       - plex.example.com
          #     secretName: cert-example-com

          # -- Custom annotations to put on the ingress resource
          annotations: {}
        pms:
          configExistingClaim: ""
          # Set to very small size
          configStorage: 2Gi
          storageClassName: proxmox-csi
        
        
        # extraVolumeMounts:
        #   - name: I think here is where I would mount the volume
        #     mountPath: /movies
          
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 