apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testthung
  namespace: argocd
spec:
  project: default
  source:
    chart: my-guestbook 
    repoURL: https://jakuboskera.github.io/charts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  

  syncPolicy:
    automated:
      prune: true
      selfHeal: true